# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gugu/w/calibre/src/calibre/gui2/dialogs/tag_categories.ui'
#
# Created: Thu Jul 19 23:32:30 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TagCategories(object):
    def setupUi(self, TagCategories):
        TagCategories.setObjectName(_fromUtf8("TagCategories"))
        TagCategories.resize(588, 482)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(I("chapters.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TagCategories.setWindowIcon(icon)
        self.gridlayout = QtGui.QGridLayout(TagCategories)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.label_3 = QtGui.QLabel(TagCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.hboxlayout.addWidget(self.label_3)
        self.category_box = QtGui.QComboBox(TagCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(160)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category_box.sizePolicy().hasHeightForWidth())
        self.category_box.setSizePolicy(sizePolicy)
        self.category_box.setMinimumSize(QtCore.QSize(145, 0))
        self.category_box.setEditable(False)
        self.category_box.setObjectName(_fromUtf8("category_box"))
        self.hboxlayout.addWidget(self.category_box)
        self.gridlayout.addLayout(self.hboxlayout, 0, 0, 1, 1)
        self.delete_category_button = QtGui.QToolButton(TagCategories)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(I("trash.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_category_button.setIcon(icon1)
        self.delete_category_button.setObjectName(_fromUtf8("delete_category_button"))
        self.gridlayout.addWidget(self.delete_category_button, 0, 1, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.input_box = QtGui.QLineEdit(TagCategories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_box.sizePolicy().hasHeightForWidth())
        self.input_box.setSizePolicy(sizePolicy)
        self.input_box.setObjectName(_fromUtf8("input_box"))
        self.hboxlayout1.addWidget(self.input_box)
        self.add_category_button = QtGui.QToolButton(TagCategories)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(I("plus.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_category_button.setIcon(icon2)
        self.add_category_button.setObjectName(_fromUtf8("add_category_button"))
        self.hboxlayout1.addWidget(self.add_category_button)
        self.gridlayout.addLayout(self.hboxlayout1, 0, 2, 1, 1)
        self.rename_category_button = QtGui.QToolButton(TagCategories)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(I("edit-undo.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rename_category_button.setIcon(icon3)
        self.rename_category_button.setObjectName(_fromUtf8("rename_category_button"))
        self.gridlayout.addWidget(self.rename_category_button, 0, 3, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.label_5 = QtGui.QLabel(TagCategories)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.hboxlayout2.addWidget(self.label_5)
        self.category_filter_box = QtGui.QComboBox(TagCategories)
        self.category_filter_box.setObjectName(_fromUtf8("category_filter_box"))
        self.hboxlayout2.addWidget(self.category_filter_box)
        self.gridlayout.addLayout(self.hboxlayout2, 1, 0, 1, 1)
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.label = QtGui.QLabel(TagCategories)
        self.label.setObjectName(_fromUtf8("label"))
        self.hboxlayout3.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem)
        self.vboxlayout.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.available_items_box = QtGui.QListWidget(TagCategories)
        self.available_items_box.setAlternatingRowColors(True)
        self.available_items_box.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.available_items_box.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.available_items_box.setObjectName(_fromUtf8("available_items_box"))
        self.hboxlayout4.addWidget(self.available_items_box)
        self.vboxlayout.addLayout(self.hboxlayout4)
        self.gridlayout.addLayout(self.vboxlayout, 2, 0, 1, 1)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem1)
        self.apply_button = QtGui.QToolButton(TagCategories)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(I("forward.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.apply_button.setIcon(icon4)
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.vboxlayout1.addWidget(self.apply_button)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem2)
        self.gridlayout.addLayout(self.vboxlayout1, 2, 1, 1, 1)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName(_fromUtf8("hboxlayout5"))
        self.label_2 = QtGui.QLabel(TagCategories)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.hboxlayout5.addWidget(self.label_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem3)
        self.vboxlayout2.addLayout(self.hboxlayout5)
        self.applied_items_box = QtGui.QListWidget(TagCategories)
        self.applied_items_box.setAlternatingRowColors(True)
        self.applied_items_box.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.applied_items_box.setObjectName(_fromUtf8("applied_items_box"))
        self.vboxlayout2.addWidget(self.applied_items_box)
        self.gridlayout.addLayout(self.vboxlayout2, 2, 2, 1, 1)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem4)
        self.unapply_button = QtGui.QToolButton(TagCategories)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(I("list_remove.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unapply_button.setIcon(icon5)
        self.unapply_button.setObjectName(_fromUtf8("unapply_button"))
        self.vboxlayout3.addWidget(self.unapply_button)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem5)
        self.gridlayout.addLayout(self.vboxlayout3, 2, 3, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(TagCategories)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 4, 0, 1, 4)
        self.label_3.setBuddy(self.category_box)
        self.label.setBuddy(self.available_items_box)
        self.label_2.setBuddy(self.applied_items_box)

        self.retranslateUi(TagCategories)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TagCategories.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TagCategories.reject)
        QtCore.QMetaObject.connectSlotsByName(TagCategories)

    def retranslateUi(self, TagCategories):
        TagCategories.setWindowTitle(_("User Categories Editor"))
        self.label_3.setText(_("Category name: "))
        self.category_box.setToolTip(_("Select a category to edit"))
        self.delete_category_button.setToolTip(_("Delete this selected tag category"))
        self.delete_category_button.setText(_("..."))
        self.input_box.setToolTip(_("Enter a category name, then use the add button or the rename button"))
        self.add_category_button.setToolTip(_("Add a new category"))
        self.add_category_button.setText(_("..."))
        self.rename_category_button.setToolTip(_("Rename the current category to what is in the box"))
        self.rename_category_button.setText(_("..."))
        self.label_5.setText(_("Category filter: "))
        self.category_filter_box.setToolTip(_("Select the content kind of the new category"))
        self.label.setText(_("A&vailable items"))
        self.apply_button.setToolTip(_("Apply tags to current tag category"))
        self.apply_button.setText(_("..."))
        self.label_2.setText(_("A&pplied items"))
        self.unapply_button.setToolTip(_("Unapply (remove) tag from current tag category"))
        self.unapply_button.setText(_("..."))

