# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kovid/work/calibre/src/calibre/gui2/dialogs/tag_editor.ui'
#
# Created: Fri May 11 09:13:10 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TagEditor(object):
    def setupUi(self, TagEditor):
        TagEditor.setObjectName(_fromUtf8("TagEditor"))
        TagEditor.resize(588, 335)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(I("chapters.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TagEditor.setWindowIcon(icon)
        self.gridlayout = QtGui.QGridLayout(TagEditor)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.label = QtGui.QLabel(TagEditor)
        self.label.setObjectName(_fromUtf8("label"))
        self.hboxlayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.delete_button = QtGui.QToolButton(TagEditor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(I("trash.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon1)
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.hboxlayout1.addWidget(self.delete_button)
        self.available_tags = QtGui.QListWidget(TagEditor)
        self.available_tags.setAlternatingRowColors(True)
        self.available_tags.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.available_tags.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.available_tags.setObjectName(_fromUtf8("available_tags"))
        self.hboxlayout1.addWidget(self.available_tags)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.gridlayout.addLayout(self.vboxlayout, 0, 0, 1, 1)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem1)
        self.apply_button = QtGui.QToolButton(TagEditor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(I("forward.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.apply_button.setIcon(icon2)
        self.apply_button.setObjectName(_fromUtf8("apply_button"))
        self.vboxlayout1.addWidget(self.apply_button)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem2)
        self.gridlayout.addLayout(self.vboxlayout1, 0, 1, 1, 1)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.label_2 = QtGui.QLabel(TagEditor)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.hboxlayout2.addWidget(self.label_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem3)
        self.vboxlayout2.addLayout(self.hboxlayout2)
        self.applied_tags = QtGui.QListWidget(TagEditor)
        self.applied_tags.setAlternatingRowColors(True)
        self.applied_tags.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.applied_tags.setObjectName(_fromUtf8("applied_tags"))
        self.vboxlayout2.addWidget(self.applied_tags)
        self.gridlayout.addLayout(self.vboxlayout2, 0, 2, 1, 1)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem4)
        self.unapply_button = QtGui.QToolButton(TagEditor)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(I("list_remove.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unapply_button.setIcon(icon3)
        self.unapply_button.setObjectName(_fromUtf8("unapply_button"))
        self.vboxlayout3.addWidget(self.unapply_button)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem5)
        self.gridlayout.addLayout(self.vboxlayout3, 0, 3, 1, 1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem6)
        self.label_3 = QtGui.QLabel(TagEditor)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.hboxlayout3.addWidget(self.label_3)
        self.add_tag_input = EnLineEdit(TagEditor)
        self.add_tag_input.setObjectName(_fromUtf8("add_tag_input"))
        self.hboxlayout3.addWidget(self.add_tag_input)
        self.add_tag_button = QtGui.QToolButton(TagEditor)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(I("plus.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_tag_button.setIcon(icon4)
        self.add_tag_button.setObjectName(_fromUtf8("add_tag_button"))
        self.hboxlayout3.addWidget(self.add_tag_button)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem7)
        self.gridlayout.addLayout(self.hboxlayout3, 1, 0, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(TagEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 2, 0, 1, 4)
        self.label.setBuddy(self.available_tags)
        self.label_2.setBuddy(self.applied_tags)
        self.label_3.setBuddy(self.add_tag_input)

        self.retranslateUi(TagEditor)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TagEditor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TagEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(TagEditor)

    def retranslateUi(self, TagEditor):
        TagEditor.setWindowTitle(_("Tag Editor"))
        self.label.setText(_("A&vailable tags"))
        self.delete_button.setToolTip(_("Delete tag from database. This will unapply the tag from all books and then remove it from the database."))
        self.delete_button.setText(_("..."))
        self.apply_button.setToolTip(_("Apply tag to current book"))
        self.apply_button.setText(_("..."))
        self.label_2.setText(_("A&pplied tags"))
        self.unapply_button.setToolTip(_("Unapply (remove) tag from current book"))
        self.unapply_button.setText(_("..."))
        self.label_3.setText(_("&Add tag:"))
        self.add_tag_input.setToolTip(_("If the tag you want is not in the available list, you can add it here. Accepts a comma separated list of tags."))
        self.add_tag_button.setToolTip(_("Add tag to available tags and apply it to current book"))
        self.add_tag_button.setText(_("..."))

from calibre.gui2.widgets import EnLineEdit

