# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kovid/work/calibre/src/calibre/gui2/store/search/search.ui'
#
# Created: Fri May 11 09:13:11 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(872, 610)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(I("store.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.top_layout = QtGui.QHBoxLayout()
        self.top_layout.setObjectName(_fromUtf8("top_layout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.top_layout.addWidget(self.label)
        self.adv_search_button = QtGui.QToolButton(Dialog)
        self.adv_search_button.setObjectName(_fromUtf8("adv_search_button"))
        self.top_layout.addWidget(self.adv_search_button)
        self.search_edit = HistoryLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_edit.sizePolicy().hasHeightForWidth())
        self.search_edit.setSizePolicy(sizePolicy)
        self.search_edit.setObjectName(_fromUtf8("search_edit"))
        self.top_layout.addWidget(self.search_edit)
        self.search = QtGui.QPushButton(Dialog)
        self.search.setObjectName(_fromUtf8("search"))
        self.top_layout.addWidget(self.search)
        self.verticalLayout_5.addLayout(self.top_layout)
        self.store_splitter = QtGui.QSplitter(Dialog)
        self.store_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.store_splitter.setObjectName(_fromUtf8("store_splitter"))
        self.groupBox = QtGui.QGroupBox(self.store_splitter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.store_list = QtGui.QScrollArea(self.groupBox)
        self.store_list.setWidgetResizable(True)
        self.store_list.setObjectName(_fromUtf8("store_list"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 193, 127))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.store_list.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.store_list)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.select_all_stores = QtGui.QPushButton(self.groupBox)
        self.select_all_stores.setObjectName(_fromUtf8("select_all_stores"))
        self.verticalLayout.addWidget(self.select_all_stores)
        self.select_invert_stores = QtGui.QPushButton(self.groupBox)
        self.select_invert_stores.setObjectName(_fromUtf8("select_invert_stores"))
        self.verticalLayout.addWidget(self.select_invert_stores)
        self.select_none_stores = QtGui.QPushButton(self.groupBox)
        self.select_none_stores.setObjectName(_fromUtf8("select_none_stores"))
        self.verticalLayout.addWidget(self.select_none_stores)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayoutWidget = QtGui.QWidget(self.store_splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.results_view = ResultsView(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results_view.sizePolicy().hasHeightForWidth())
        self.results_view.setSizePolicy(sizePolicy)
        self.results_view.setMinimumSize(QtCore.QSize(0, 0))
        self.results_view.setAlternatingRowColors(True)
        self.results_view.setIconSize(QtCore.QSize(32, 32))
        self.results_view.setRootIsDecorated(False)
        self.results_view.setUniformRowHeights(False)
        self.results_view.setItemsExpandable(False)
        self.results_view.setSortingEnabled(True)
        self.results_view.setExpandsOnDoubleClick(False)
        self.results_view.setObjectName(_fromUtf8("results_view"))
        self.results_view.header().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.results_view)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.configure = QtGui.QToolButton(self.verticalLayoutWidget)
        self.configure.setObjectName(_fromUtf8("configure"))
        self.horizontalLayout.addWidget(self.configure)
        self.open_external = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.open_external.setObjectName(_fromUtf8("open_external"))
        self.horizontalLayout.addWidget(self.open_external)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.store_splitter)
        self.bottom_layout = QtGui.QHBoxLayout()
        self.bottom_layout.setObjectName(_fromUtf8("bottom_layout"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.bottom_layout.addWidget(self.label_2)
        self.total = QtGui.QLabel(Dialog)
        self.total.setObjectName(_fromUtf8("total"))
        self.bottom_layout.addWidget(self.total)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottom_layout.addItem(spacerItem1)
        self.close = QtGui.QPushButton(Dialog)
        self.close.setObjectName(_fromUtf8("close"))
        self.bottom_layout.addWidget(self.close)
        self.verticalLayout_5.addLayout(self.bottom_layout)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.close, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.search_edit, self.search)
        Dialog.setTabOrder(self.search, self.results_view)
        Dialog.setTabOrder(self.results_view, self.store_list)
        Dialog.setTabOrder(self.store_list, self.select_all_stores)
        Dialog.setTabOrder(self.select_all_stores, self.select_invert_stores)
        Dialog.setTabOrder(self.select_invert_stores, self.select_none_stores)
        Dialog.setTabOrder(self.select_none_stores, self.configure)
        Dialog.setTabOrder(self.configure, self.open_external)
        Dialog.setTabOrder(self.open_external, self.close)
        Dialog.setTabOrder(self.close, self.adv_search_button)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_("Get Books"))
        self.label.setText(_("Query:"))
        self.adv_search_button.setText(_("..."))
        self.search.setText(_("Search"))
        self.groupBox.setTitle(_("Stores"))
        self.select_all_stores.setText(_("All"))
        self.select_invert_stores.setText(_("Invert"))
        self.select_none_stores.setText(_("None"))
        self.configure.setText(_("..."))
        self.open_external.setToolTip(_("Open a selected book in the system\'s web browser"))
        self.open_external.setText(_("Open in &external browser"))
        self.label_2.setText(_("Books:"))
        self.total.setText(_("0"))
        self.close.setText(_("Close"))

from calibre.gui2.widgets import HistoryLineEdit
from results_view import ResultsView

