# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gugu/w/calibre/src/calibre/gui2/catalog/catalog_epub_mobi.ui'
#
# Created: Thu Jul 19 23:32:29 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(650, 596)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.includedSections = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.includedSections.sizePolicy().hasHeightForWidth())
        self.includedSections.setSizePolicy(sizePolicy)
        self.includedSections.setMinimumSize(QtCore.QSize(0, 0))
        self.includedSections.setObjectName(_fromUtf8("includedSections"))
        self.gridLayout_2 = QtGui.QGridLayout(self.includedSections)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.generate_genres = QtGui.QCheckBox(self.includedSections)
        self.generate_genres.setObjectName(_fromUtf8("generate_genres"))
        self.gridLayout_2.addWidget(self.generate_genres, 0, 1, 1, 1)
        self.generate_recently_added = QtGui.QCheckBox(self.includedSections)
        self.generate_recently_added.setObjectName(_fromUtf8("generate_recently_added"))
        self.gridLayout_2.addWidget(self.generate_recently_added, 4, 1, 1, 1)
        self.generate_descriptions = QtGui.QCheckBox(self.includedSections)
        self.generate_descriptions.setObjectName(_fromUtf8("generate_descriptions"))
        self.gridLayout_2.addWidget(self.generate_descriptions, 5, 1, 1, 1)
        self.generate_series = QtGui.QCheckBox(self.includedSections)
        self.generate_series.setObjectName(_fromUtf8("generate_series"))
        self.gridLayout_2.addWidget(self.generate_series, 5, 0, 1, 1)
        self.generate_titles = QtGui.QCheckBox(self.includedSections)
        self.generate_titles.setObjectName(_fromUtf8("generate_titles"))
        self.gridLayout_2.addWidget(self.generate_titles, 4, 0, 1, 1)
        self.generate_authors = QtGui.QCheckBox(self.includedSections)
        self.generate_authors.setEnabled(True)
        self.generate_authors.setChecked(False)
        self.generate_authors.setObjectName(_fromUtf8("generate_authors"))
        self.gridLayout_2.addWidget(self.generate_authors, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.includedSections)
        self.excludedGenres = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.excludedGenres.sizePolicy().hasHeightForWidth())
        self.excludedGenres.setSizePolicy(sizePolicy)
        self.excludedGenres.setMinimumSize(QtCore.QSize(0, 0))
        self.excludedGenres.setObjectName(_fromUtf8("excludedGenres"))
        self.formLayout_3 = QtGui.QFormLayout(self.excludedGenres)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(-1)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.excludedGenres)
        self.label.setMinimumSize(QtCore.QSize(175, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.exclude_genre = QtGui.QLineEdit(self.excludedGenres)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exclude_genre.sizePolicy().hasHeightForWidth())
        self.exclude_genre.setSizePolicy(sizePolicy)
        self.exclude_genre.setMinimumSize(QtCore.QSize(0, 0))
        self.exclude_genre.setToolTip(_fromUtf8(""))
        self.exclude_genre.setObjectName(_fromUtf8("exclude_genre"))
        self.horizontalLayout.addWidget(self.exclude_genre)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout)
        self.verticalLayout.addWidget(self.excludedGenres)
        self.excludedBooks = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.excludedBooks.sizePolicy().hasHeightForWidth())
        self.excludedBooks.setSizePolicy(sizePolicy)
        self.excludedBooks.setMinimumSize(QtCore.QSize(0, 0))
        self.excludedBooks.setObjectName(_fromUtf8("excludedBooks"))
        self.formLayout = QtGui.QFormLayout(self.excludedBooks)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.excludedBooks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(175, 0))
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.exclude_tags = QtGui.QLineEdit(self.excludedBooks)
        self.exclude_tags.setMinimumSize(QtCore.QSize(0, 0))
        self.exclude_tags.setObjectName(_fromUtf8("exclude_tags"))
        self.horizontalLayout_3.addWidget(self.exclude_tags)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_3)
        self.exclude_spec_hl = QtGui.QHBoxLayout()
        self.exclude_spec_hl.setObjectName(_fromUtf8("exclude_spec_hl"))
        self.label_7 = QtGui.QLabel(self.excludedBooks)
        self.label_7.setMinimumSize(QtCore.QSize(175, 0))
        self.label_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.exclude_spec_hl.addWidget(self.label_7)
        self.exclude_source_field = QtGui.QComboBox(self.excludedBooks)
        self.exclude_source_field.setMinimumSize(QtCore.QSize(0, 0))
        self.exclude_source_field.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.exclude_source_field.setMinimumContentsLength(18)
        self.exclude_source_field.setObjectName(_fromUtf8("exclude_source_field"))
        self.exclude_spec_hl.addWidget(self.exclude_source_field)
        self.exclude_pattern = QtGui.QLineEdit(self.excludedBooks)
        self.exclude_pattern.setMinimumSize(QtCore.QSize(150, 0))
        self.exclude_pattern.setObjectName(_fromUtf8("exclude_pattern"))
        self.exclude_spec_hl.addWidget(self.exclude_pattern)
        self.formLayout.setLayout(2, QtGui.QFormLayout.SpanningRole, self.exclude_spec_hl)
        self.verticalLayout.addWidget(self.excludedBooks)
        self.readBooks = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readBooks.sizePolicy().hasHeightForWidth())
        self.readBooks.setSizePolicy(sizePolicy)
        self.readBooks.setMinimumSize(QtCore.QSize(0, 0))
        self.readBooks.setObjectName(_fromUtf8("readBooks"))
        self.formLayout_2 = QtGui.QFormLayout(self.readBooks)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.read_spec_hl = QtGui.QHBoxLayout()
        self.read_spec_hl.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.read_spec_hl.setObjectName(_fromUtf8("read_spec_hl"))
        self.label_3 = QtGui.QLabel(self.readBooks)
        self.label_3.setMinimumSize(QtCore.QSize(175, 0))
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.read_spec_hl.addWidget(self.label_3)
        self.read_source_field = QtGui.QComboBox(self.readBooks)
        self.read_source_field.setMinimumSize(QtCore.QSize(0, 0))
        self.read_source_field.setStatusTip(_fromUtf8(""))
        self.read_source_field.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.read_source_field.setMinimumContentsLength(18)
        self.read_source_field.setObjectName(_fromUtf8("read_source_field"))
        self.read_spec_hl.addWidget(self.read_source_field)
        self.read_pattern = QtGui.QLineEdit(self.readBooks)
        self.read_pattern.setMinimumSize(QtCore.QSize(150, 0))
        self.read_pattern.setStatusTip(_fromUtf8(""))
        self.read_pattern.setObjectName(_fromUtf8("read_pattern"))
        self.read_spec_hl.addWidget(self.read_pattern)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.SpanningRole, self.read_spec_hl)
        self.verticalLayout.addWidget(self.readBooks)
        self.otherOptions = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otherOptions.sizePolicy().hasHeightForWidth())
        self.otherOptions.setSizePolicy(sizePolicy)
        self.otherOptions.setMinimumSize(QtCore.QSize(0, 0))
        self.otherOptions.setObjectName(_fromUtf8("otherOptions"))
        self.formLayout_4 = QtGui.QFormLayout(self.otherOptions)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.otherOptions)
        self.label_5.setMinimumSize(QtCore.QSize(175, 0))
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setToolTip(_fromUtf8(""))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.wishlist_tag = QtGui.QLineEdit(self.otherOptions)
        self.wishlist_tag.setObjectName(_fromUtf8("wishlist_tag"))
        self.horizontalLayout_2.addWidget(self.wishlist_tag)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.otherOptions)
        self.label_4.setMinimumSize(QtCore.QSize(175, 0))
        self.label_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.thumb_width = QtGui.QDoubleSpinBox(self.otherOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumb_width.sizePolicy().hasHeightForWidth())
        self.thumb_width.setSizePolicy(sizePolicy)
        self.thumb_width.setDecimals(2)
        self.thumb_width.setMinimum(1.0)
        self.thumb_width.setMaximum(2.0)
        self.thumb_width.setSingleStep(0.1)
        self.thumb_width.setObjectName(_fromUtf8("thumb_width"))
        self.horizontalLayout_4.addWidget(self.thumb_width)
        self.formLayout_4.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.otherOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(175, 0))
        self.label_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_6.setToolTip(_fromUtf8(""))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.header_note_source_field = QtGui.QComboBox(self.otherOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_note_source_field.sizePolicy().hasHeightForWidth())
        self.header_note_source_field.setSizePolicy(sizePolicy)
        self.header_note_source_field.setMinimumSize(QtCore.QSize(0, 0))
        self.header_note_source_field.setObjectName(_fromUtf8("header_note_source_field"))
        self.horizontalLayout_5.addWidget(self.header_note_source_field)
        self.formLayout_4.setLayout(3, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.otherOptions)
        self.label_9.setMinimumSize(QtCore.QSize(175, 0))
        self.label_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.merge_source_field = QtGui.QComboBox(self.otherOptions)
        self.merge_source_field.setMinimumSize(QtCore.QSize(0, 0))
        self.merge_source_field.setObjectName(_fromUtf8("merge_source_field"))
        self.horizontalLayout_7.addWidget(self.merge_source_field)
        self.line_2 = QtGui.QFrame(self.otherOptions)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_7.addWidget(self.line_2)
        self.merge_before = QtGui.QRadioButton(self.otherOptions)
        self.merge_before.setObjectName(_fromUtf8("merge_before"))
        self.horizontalLayout_7.addWidget(self.merge_before)
        self.merge_after = QtGui.QRadioButton(self.otherOptions)
        self.merge_after.setObjectName(_fromUtf8("merge_after"))
        self.horizontalLayout_7.addWidget(self.merge_after)
        self.line = QtGui.QFrame(self.otherOptions)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_7.addWidget(self.line)
        self.include_hr = QtGui.QCheckBox(self.otherOptions)
        self.include_hr.setObjectName(_fromUtf8("include_hr"))
        self.horizontalLayout_7.addWidget(self.include_hr)
        self.formLayout_4.setLayout(4, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.otherOptions)
        self.label.setBuddy(self.exclude_genre)
        self.label_2.setBuddy(self.exclude_tags)
        self.label_7.setBuddy(self.exclude_source_field)
        self.label_3.setBuddy(self.read_source_field)
        self.label_5.setBuddy(self.wishlist_tag)
        self.label_4.setBuddy(self.thumb_width)
        self.label_6.setBuddy(self.header_note_source_field)
        self.label_9.setBuddy(self.merge_source_field)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_("Form"))
        self.includedSections.setToolTip(_("Sections to include in catalog."))
        self.includedSections.setTitle(_("Included sections"))
        self.generate_genres.setText(_("Books by &Genre"))
        self.generate_recently_added.setText(_("Recently &Added"))
        self.generate_descriptions.setText(_("&Descriptions"))
        self.generate_series.setText(_("Books by &Series"))
        self.generate_titles.setText(_("Books by &Title"))
        self.generate_authors.setText(_("Books by Author"))
        self.excludedGenres.setToolTip(_("<p>Default pattern \n"
"\\[.+\\]\n"
"excludes tags of the form [tag], \n"
"e.g., [Project Gutenberg]</p>"))
        self.excludedGenres.setTitle(_("Excluded genres"))
        self.label.setText(_("Tags to &exclude"))
        self.excludedBooks.setToolTip(_("Books matching either pattern will not be included in generated catalog. "))
        self.excludedBooks.setTitle(_("Excluded books"))
        self.label_2.setText(_("Tags to &exclude"))
        self.exclude_tags.setToolTip(_("<p>Comma-separated list of tags to exclude.\n"
"Default: ~,Catalog"))
        self.label_7.setText(_("&Column/value"))
        self.exclude_source_field.setToolTip(_("Column containing additional exclusion criteria"))
        self.exclude_pattern.setToolTip(_("Exclusion pattern"))
        self.readBooks.setToolTip(_("Matching books will be displayed with a check mark"))
        self.readBooks.setTitle(_("Read books"))
        self.label_3.setText(_("&Column/value"))
        self.read_source_field.setToolTip(_("Column containing \'read\' status"))
        self.read_pattern.setToolTip(_("\'read book\' pattern"))
        self.otherOptions.setTitle(_("Other options"))
        self.label_5.setText(_("&Wishlist tag"))
        self.wishlist_tag.setToolTip(_("Books tagged as Wishlist items will be displayed with an X"))
        self.label_4.setText(_("&Thumbnail width"))
        self.thumb_width.setToolTip(_("Size hint for Description cover thumbnails"))
        self.thumb_width.setSuffix(_(" inch"))
        self.label_6.setText(_("&Description note"))
        self.header_note_source_field.setToolTip(_("Custom column source for note to include in Description header area"))
        self.label_9.setText(_("&Merge with Comments"))
        self.merge_source_field.setToolTip(_("Additional content merged with Comments during catalog generation"))
        self.merge_before.setToolTip(_("Merge additional content before Comments"))
        self.merge_before.setText(_("&Before"))
        self.merge_after.setToolTip(_("Merge additional content after Comments"))
        self.merge_after.setText(_("&After"))
        self.include_hr.setToolTip(_("Separate Comments and additional content with horizontal rule"))
        self.include_hr.setText(_("&Separator"))

