# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gugu/w/calibre/src/calibre/gui2/convert/comic_input.ui'
#
# Created: Thu Jul 19 23:32:30 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(599, 398)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.opt_colors = QtGui.QSpinBox(Form)
        self.opt_colors.setMinimum(8)
        self.opt_colors.setMaximum(32000000)
        self.opt_colors.setSingleStep(8)
        self.opt_colors.setObjectName(_fromUtf8("opt_colors"))
        self.gridLayout.addWidget(self.opt_colors, 3, 1, 1, 1)
        self.opt_dont_normalize = QtGui.QCheckBox(Form)
        self.opt_dont_normalize.setObjectName(_fromUtf8("opt_dont_normalize"))
        self.gridLayout.addWidget(self.opt_dont_normalize, 5, 0, 1, 1)
        self.opt_keep_aspect_ratio = QtGui.QCheckBox(Form)
        self.opt_keep_aspect_ratio.setObjectName(_fromUtf8("opt_keep_aspect_ratio"))
        self.gridLayout.addWidget(self.opt_keep_aspect_ratio, 6, 0, 1, 1)
        self.opt_dont_sharpen = QtGui.QCheckBox(Form)
        self.opt_dont_sharpen.setObjectName(_fromUtf8("opt_dont_sharpen"))
        self.gridLayout.addWidget(self.opt_dont_sharpen, 7, 0, 1, 1)
        self.opt_disable_trim = QtGui.QCheckBox(Form)
        self.opt_disable_trim.setObjectName(_fromUtf8("opt_disable_trim"))
        self.gridLayout.addWidget(self.opt_disable_trim, 8, 0, 1, 1)
        self.opt_wide = QtGui.QCheckBox(Form)
        self.opt_wide.setObjectName(_fromUtf8("opt_wide"))
        self.gridLayout.addWidget(self.opt_wide, 9, 0, 1, 1)
        self.opt_landscape = QtGui.QCheckBox(Form)
        self.opt_landscape.setObjectName(_fromUtf8("opt_landscape"))
        self.gridLayout.addWidget(self.opt_landscape, 10, 0, 1, 1)
        self.opt_right2left = QtGui.QCheckBox(Form)
        self.opt_right2left.setObjectName(_fromUtf8("opt_right2left"))
        self.gridLayout.addWidget(self.opt_right2left, 11, 0, 1, 1)
        self.opt_no_sort = QtGui.QCheckBox(Form)
        self.opt_no_sort.setObjectName(_fromUtf8("opt_no_sort"))
        self.gridLayout.addWidget(self.opt_no_sort, 12, 0, 1, 1)
        self.opt_despeckle = QtGui.QCheckBox(Form)
        self.opt_despeckle.setObjectName(_fromUtf8("opt_despeckle"))
        self.gridLayout.addWidget(self.opt_despeckle, 13, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 15, 0, 1, 1)
        self.opt_no_process = QtGui.QCheckBox(Form)
        self.opt_no_process.setObjectName(_fromUtf8("opt_no_process"))
        self.gridLayout.addWidget(self.opt_no_process, 0, 0, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 14, 0, 1, 1)
        self.opt_output_format = QtGui.QComboBox(Form)
        self.opt_output_format.setObjectName(_fromUtf8("opt_output_format"))
        self.gridLayout.addWidget(self.opt_output_format, 14, 1, 1, 1)
        self.opt_dont_grayscale = QtGui.QCheckBox(Form)
        self.opt_dont_grayscale.setObjectName(_fromUtf8("opt_dont_grayscale"))
        self.gridLayout.addWidget(self.opt_dont_grayscale, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.opt_comic_image_size = QtGui.QLineEdit(Form)
        self.opt_comic_image_size.setObjectName(_fromUtf8("opt_comic_image_size"))
        self.gridLayout.addWidget(self.opt_comic_image_size, 4, 1, 1, 1)
        self.opt_dont_add_comic_pages_to_toc = QtGui.QCheckBox(Form)
        self.opt_dont_add_comic_pages_to_toc.setObjectName(_fromUtf8("opt_dont_add_comic_pages_to_toc"))
        self.gridLayout.addWidget(self.opt_dont_add_comic_pages_to_toc, 2, 0, 1, 2)
        self.label_3.setBuddy(self.opt_colors)
        self.label.setBuddy(self.opt_output_format)
        self.label_2.setBuddy(self.opt_comic_image_size)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_3.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_colors.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_dont_normalize.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_keep_aspect_ratio.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_dont_sharpen.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_disable_trim.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_wide.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_landscape.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_right2left.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_no_sort.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_despeckle.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_output_format.setDisabled)
        QtCore.QObject.connect(self.opt_no_process, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_dont_grayscale.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_("Form"))
        self.label_3.setText(_("&Number of Colors:"))
        self.opt_dont_normalize.setText(_("Disable &normalize"))
        self.opt_keep_aspect_ratio.setText(_("Keep &aspect ratio"))
        self.opt_dont_sharpen.setText(_("Disable &Sharpening"))
        self.opt_disable_trim.setText(_("Disable &Trimming"))
        self.opt_wide.setText(_("&Wide"))
        self.opt_landscape.setText(_("&Landscape"))
        self.opt_right2left.setText(_("&Right to left"))
        self.opt_no_sort.setText(_("Don\'t so&rt"))
        self.opt_despeckle.setText(_("De&speckle"))
        self.opt_no_process.setText(_("&Disable comic processing"))
        self.label.setText(_("&Output format:"))
        self.opt_dont_grayscale.setText(_("Disable conversion of images to &black and white"))
        self.label_2.setText(_("Override image  &size:"))
        self.opt_dont_add_comic_pages_to_toc.setText(_("Don\'t add links to &pages to the Table of Contents for CBC files"))

