# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gugu/w/calibre/src/calibre/gui2/convert/page_setup.ui'
#
# Created: Thu Jul 19 23:32:30 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(572, 476)
        self.verticalLayout_4 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.opt_output_profile = QtGui.QListView(Form)
        self.opt_output_profile.setObjectName(_fromUtf8("opt_output_profile"))
        self.verticalLayout_2.addWidget(self.opt_output_profile)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.profile_description = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_description.sizePolicy().hasHeightForWidth())
        self.profile_description.setSizePolicy(sizePolicy)
        self.profile_description.setText(_fromUtf8(""))
        self.profile_description.setWordWrap(True)
        self.profile_description.setObjectName(_fromUtf8("profile_description"))
        self.verticalLayout.addWidget(self.profile_description)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.opt_input_profile = QtGui.QListView(Form)
        self.opt_input_profile.setObjectName(_fromUtf8("opt_input_profile"))
        self.verticalLayout_3.addWidget(self.opt_input_profile)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.opt_margin_left = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.opt_margin_left.setDecimals(1)
        self.opt_margin_left.setMinimum(-1.0)
        self.opt_margin_left.setMaximum(200.0)
        self.opt_margin_left.setObjectName(_fromUtf8("opt_margin_left"))
        self.gridLayout.addWidget(self.opt_margin_left, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.opt_margin_top = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.opt_margin_top.setDecimals(1)
        self.opt_margin_top.setMinimum(-1.0)
        self.opt_margin_top.setMaximum(200.0)
        self.opt_margin_top.setObjectName(_fromUtf8("opt_margin_top"))
        self.gridLayout.addWidget(self.opt_margin_top, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.opt_margin_right = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.opt_margin_right.setDecimals(1)
        self.opt_margin_right.setMinimum(-1.0)
        self.opt_margin_right.setMaximum(200.0)
        self.opt_margin_right.setObjectName(_fromUtf8("opt_margin_right"))
        self.gridLayout.addWidget(self.opt_margin_right, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.opt_margin_bottom = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.opt_margin_bottom.setDecimals(1)
        self.opt_margin_bottom.setMinimum(-1.0)
        self.opt_margin_bottom.setMaximum(200.0)
        self.opt_margin_bottom.setObjectName(_fromUtf8("opt_margin_bottom"))
        self.gridLayout.addWidget(self.opt_margin_bottom, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.opt_output_profile)
        self.label_2.setBuddy(self.opt_input_profile)
        self.label_3.setBuddy(self.opt_margin_left)
        self.label_4.setBuddy(self.opt_margin_top)
        self.label_5.setBuddy(self.opt_margin_right)
        self.label_6.setBuddy(self.opt_margin_bottom)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_("Form"))
        self.label.setText(_("&Output profile:"))
        self.groupBox.setTitle(_("Profile description"))
        self.label_2.setText(_("&Input profile:"))
        self.groupBox_2.setTitle(_("Margins"))
        self.label_3.setText(_("&Left:"))
        self.opt_margin_left.setSpecialValueText(_("No margin"))
        self.opt_margin_left.setSuffix(_(" pt"))
        self.label_4.setText(_("&Top:"))
        self.opt_margin_top.setSpecialValueText(_("No margin"))
        self.opt_margin_top.setSuffix(_(" pt"))
        self.label_5.setText(_("&Right:"))
        self.opt_margin_right.setSpecialValueText(_("No margin"))
        self.opt_margin_right.setSuffix(_(" pt"))
        self.label_6.setText(_("&Bottom:"))
        self.opt_margin_bottom.setSpecialValueText(_("No margin"))
        self.opt_margin_bottom.setSuffix(_(" pt"))

