# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gugu/w/calibre/src/calibre/gui2/filename_pattern.ui'
#
# Created: Thu Jul 19 23:32:28 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(335, 570)
        self.vboxlayout = QtGui.QVBoxLayout(Form)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.label = QtGui.QLabel(Form)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.vboxlayout.addWidget(self.label)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.re = QtGui.QComboBox(self.groupBox)
        self.re.setEditable(True)
        self.re.setMaxCount(10)
        self.re.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.re.setObjectName(_fromUtf8("re"))
        self.vboxlayout1.addWidget(self.re)
        self.vboxlayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.hboxlayout1.addWidget(self.label_2)
        self.filename = QtGui.QLineEdit(self.groupBox_2)
        self.filename.setObjectName(_fromUtf8("filename"))
        self.hboxlayout1.addWidget(self.filename)
        self.hboxlayout.addLayout(self.hboxlayout1)
        self.test_button = QtGui.QPushButton(self.groupBox_2)
        self.test_button.setObjectName(_fromUtf8("test_button"))
        self.hboxlayout.addWidget(self.test_button)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 305, 263))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.title = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.title.setReadOnly(True)
        self.title.setObjectName(_fromUtf8("title"))
        self.gridLayout_2.addWidget(self.title, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.authors = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.authors.setReadOnly(True)
        self.authors.setObjectName(_fromUtf8("authors"))
        self.gridLayout_2.addWidget(self.authors, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.series = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.series.setReadOnly(True)
        self.series.setObjectName(_fromUtf8("series"))
        self.gridLayout_2.addWidget(self.series, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.series_index = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.series_index.setReadOnly(True)
        self.series_index.setObjectName(_fromUtf8("series_index"))
        self.gridLayout_2.addWidget(self.series_index, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.isbn = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.isbn.setReadOnly(True)
        self.isbn.setObjectName(_fromUtf8("isbn"))
        self.gridLayout_2.addWidget(self.isbn, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.publisher = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.publisher.setReadOnly(True)
        self.publisher.setObjectName(_fromUtf8("publisher"))
        self.gridLayout_2.addWidget(self.publisher, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.pubdate = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.pubdate.setReadOnly(True)
        self.pubdate.setObjectName(_fromUtf8("pubdate"))
        self.gridLayout_2.addWidget(self.pubdate, 6, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.vboxlayout.addWidget(self.groupBox_2)
        self.label_2.setBuddy(self.filename)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_("Form"))
        self.label.setText(_("<div style=\"font-size:10pt;\">\n"
"<p>Set a regular expression pattern to use when trying to guess ebook metadata from filenames. </p>\n"
"<p>A <a href=\"http://manual.calibre-ebook.com/regexp.html\">tutorial</a> on using regular expressions is available.</p>\n"
"<p>Use the <b>Test</b> functionality below to test your regular expression on a few sample filenames (remember to include the file extension). The group names for the various metadata entries are documented in tooltips.</p></div>"))
        self.groupBox.setTitle(_("Regular &expression"))
        self.groupBox_2.setTitle(_("&Test"))
        self.label_2.setText(_("File &name:"))
        self.test_button.setText(_("Test"))
        self.label_3.setText(_("Title:"))
        self.title.setToolTip(_("Regular expression (?P<title>)"))
        self.title.setText(_("No match"))
        self.label_4.setText(_("Authors:"))
        self.authors.setToolTip(_("Regular expression (?P<author>)"))
        self.authors.setText(_("No match"))
        self.label_5.setText(_("Series:"))
        self.series.setToolTip(_("Regular expression (?P<series>)"))
        self.series.setText(_("No match"))
        self.label_6.setText(_("Series index:"))
        self.series_index.setToolTip(_("Regular expression (?P<series_index>)"))
        self.series_index.setText(_("No match"))
        self.label_7.setText(_("ISBN:"))
        self.isbn.setToolTip(_("Regular expression (?P<isbn>)"))
        self.isbn.setText(_("No match"))
        self.label_8.setText(_("Publisher:"))
        self.publisher.setToolTip(_("Regular expression (?P<publisher>)"))
        self.publisher.setText(_("No match"))
        self.label_9.setText(_("Published:"))
        self.pubdate.setToolTip(_("Regular expression (?P<published>)"))
        self.pubdate.setText(_("No match"))

