# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kovid/work/calibre/src/calibre/gui2/preferences/metadata_sources.ui'
#
# Created: Tue Sep 27 22:11:08 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(781, 394)
        Form.setWindowTitle(_("Form"))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stack = QtGui.QStackedWidget(Form)
        self.stack.setObjectName(_fromUtf8("stack"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout = QtGui.QGridLayout(self.page)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setTitle(_("Metadata sources"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(_("Disable any metadata sources you do not want by unchecking them. You can also set the cover priority. Covers from sources that have a higher (smaller) priority will be preferred when bulk downloading metadata.\n"
""))
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.sources_view = QtGui.QTableView(self.groupBox)
        self.sources_view.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.sources_view.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.sources_view.setObjectName(_fromUtf8("sources_view"))
        self.verticalLayout_3.addWidget(self.sources_view)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setText(_("Sources with a red X next to their names must be configured before they will be used. "))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.configure_plugin_button = QtGui.QPushButton(self.groupBox)
        self.configure_plugin_button.setText(_("Configure selected source"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(I("plugins.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.configure_plugin_button.setIcon(icon)
        self.configure_plugin_button.setObjectName(_fromUtf8("configure_plugin_button"))
        self.verticalLayout_3.addWidget(self.configure_plugin_button)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 7, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.page)
        self.groupBox_2.setTitle(_("Downloaded metadata fields"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.fields_view = QtGui.QListView(self.groupBox_2)
        self.fields_view.setToolTip(_("If you uncheck any fields, metadata for those fields will not be downloaded"))
        self.fields_view.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.fields_view.setObjectName(_fromUtf8("fields_view"))
        self.gridLayout_2.addWidget(self.fields_view, 0, 0, 1, 2)
        self.select_all_button = QtGui.QPushButton(self.groupBox_2)
        self.select_all_button.setText(_("&Select all"))
        self.select_all_button.setObjectName(_fromUtf8("select_all_button"))
        self.gridLayout_2.addWidget(self.select_all_button, 1, 0, 1, 1)
        self.clear_all_button = QtGui.QPushButton(self.groupBox_2)
        self.clear_all_button.setText(_("&Clear all"))
        self.clear_all_button.setObjectName(_fromUtf8("clear_all_button"))
        self.gridLayout_2.addWidget(self.clear_all_button, 1, 1, 1, 1)
        self.select_default_button = QtGui.QPushButton(self.groupBox_2)
        self.select_default_button.setText(_("&Select default"))
        self.select_default_button.setToolTip(_("Restore your own subset of checked fields that you define using the \'Set as default\' button"))
        self.select_default_button.setObjectName(_fromUtf8("select_default_button"))
        self.gridLayout_2.addWidget(self.select_default_button, 2, 0, 1, 1)
        self.set_as_default_button = QtGui.QPushButton(self.groupBox_2)
        self.set_as_default_button.setText(_("&Set as default"))
        self.set_as_default_button.setToolTip(_("Store the currently checked fields as a default you can restore using the \'Select default\' button"))
        self.set_as_default_button.setObjectName(_fromUtf8("set_as_default_button"))
        self.gridLayout_2.addWidget(self.set_as_default_button, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 2)
        self.opt_txt_comments = QtGui.QCheckBox(self.page)
        self.opt_txt_comments.setText(_("Convert all downloaded comments to plain &text"))
        self.opt_txt_comments.setObjectName(_fromUtf8("opt_txt_comments"))
        self.gridLayout.addWidget(self.opt_txt_comments, 1, 1, 1, 2)
        self.opt_swap_author_names = QtGui.QCheckBox(self.page)
        self.opt_swap_author_names.setText(_("Swap author names from FN LN to LN, FN"))
        self.opt_swap_author_names.setObjectName(_fromUtf8("opt_swap_author_names"))
        self.gridLayout.addWidget(self.opt_swap_author_names, 2, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setText(_("Max. number of &tags to download:"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 1, 1, 1)
        self.opt_max_tags = QtGui.QSpinBox(self.page)
        self.opt_max_tags.setObjectName(_fromUtf8("opt_max_tags"))
        self.gridLayout.addWidget(self.opt_max_tags, 4, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setText(_("Max. &time to wait after first match is found:"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        self.opt_wait_after_first_identify_result = QtGui.QSpinBox(self.page)
        self.opt_wait_after_first_identify_result.setSuffix(_(" secs"))
        self.opt_wait_after_first_identify_result.setObjectName(_fromUtf8("opt_wait_after_first_identify_result"))
        self.gridLayout.addWidget(self.opt_wait_after_first_identify_result, 5, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setText(_("Max. time to wait after first &cover is found:"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 1, 1, 1)
        self.opt_wait_after_first_cover_result = QtGui.QSpinBox(self.page)
        self.opt_wait_after_first_cover_result.setSuffix(_(" secs"))
        self.opt_wait_after_first_cover_result.setObjectName(_fromUtf8("opt_wait_after_first_cover_result"))
        self.gridLayout.addWidget(self.opt_wait_after_first_cover_result, 6, 2, 1, 1)
        self.opt_fewer_tags = QtGui.QCheckBox(self.page)
        self.opt_fewer_tags.setToolTip(_("<p>Different metadata sources have different sets of tags for the same book. If this option is checked, then calibre will use the smaller tag sets. These tend to be more like genres, while the larger tag sets tend to describe the books content.\n"
"<p>Note that this option will only make a practical difference if one of the metadata sources has a genre like tag set for the book you are searching for. Most often, they all have large tag sets."))
        self.opt_fewer_tags.setText(_("Prefer &fewer tags"))
        self.opt_fewer_tags.setObjectName(_fromUtf8("opt_fewer_tags"))
        self.gridLayout.addWidget(self.opt_fewer_tags, 3, 1, 1, 2)
        self.stack.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stack.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stack)
        self.label_2.setBuddy(self.opt_max_tags)
        self.label_3.setBuddy(self.opt_wait_after_first_identify_result)
        self.label_4.setBuddy(self.opt_wait_after_first_cover_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass


