# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gugu/w/calibre/src/calibre/gui2/preferences/server.ui'
#
# Created: Thu Jul 19 23:32:29 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(641, 563)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.opt_username = QtGui.QLineEdit(Form)
        self.opt_username.setObjectName(_fromUtf8("opt_username"))
        self.gridLayout_5.addWidget(self.opt_username, 1, 1, 1, 2)
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 2, 0, 1, 1)
        self.opt_password = QtGui.QLineEdit(Form)
        self.opt_password.setObjectName(_fromUtf8("opt_password"))
        self.gridLayout_5.addWidget(self.opt_password, 2, 1, 1, 1)
        self.opt_max_cover = QtGui.QLineEdit(Form)
        self.opt_max_cover.setText(_fromUtf8(""))
        self.opt_max_cover.setObjectName(_fromUtf8("opt_max_cover"))
        self.gridLayout_5.addWidget(self.opt_max_cover, 4, 1, 1, 2)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.opt_port = QtGui.QSpinBox(Form)
        self.opt_port.setMaximum(65535)
        self.opt_port.setProperty("value", 8080)
        self.opt_port.setObjectName(_fromUtf8("opt_port"))
        self.gridLayout_5.addWidget(self.opt_port, 0, 1, 1, 2)
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.show_server_password = QtGui.QCheckBox(Form)
        self.show_server_password.setObjectName(_fromUtf8("show_server_password"))
        self.gridLayout_5.addWidget(self.show_server_password, 3, 1, 1, 2)
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 5, 0, 1, 1)
        self.opt_max_opds_items = QtGui.QSpinBox(Form)
        self.opt_max_opds_items.setMinimum(10)
        self.opt_max_opds_items.setMaximum(10000)
        self.opt_max_opds_items.setObjectName(_fromUtf8("opt_max_opds_items"))
        self.gridLayout_5.addWidget(self.opt_max_opds_items, 5, 1, 1, 2)
        self.opt_max_opds_ungrouped_items = QtGui.QSpinBox(Form)
        self.opt_max_opds_ungrouped_items.setMinimum(25)
        self.opt_max_opds_ungrouped_items.setMaximum(1000000)
        self.opt_max_opds_ungrouped_items.setObjectName(_fromUtf8("opt_max_opds_ungrouped_items"))
        self.gridLayout_5.addWidget(self.opt_max_opds_ungrouped_items, 6, 1, 1, 2)
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 6, 0, 1, 1)
        self.label_164 = QtGui.QLabel(Form)
        self.label_164.setObjectName(_fromUtf8("label_164"))
        self.gridLayout_5.addWidget(self.label_164, 7, 0, 1, 1)
        self.opt_cs_restriction = QtGui.QComboBox(Form)
        self.opt_cs_restriction.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.opt_cs_restriction.setMinimumContentsLength(20)
        self.opt_cs_restriction.setObjectName(_fromUtf8("opt_cs_restriction"))
        self.gridLayout_5.addWidget(self.opt_cs_restriction, 7, 1, 1, 2)
        self.label = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("QLabel {color:red}"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 8, 0, 1, 1)
        self.opt_url_prefix = QtGui.QLineEdit(Form)
        self.opt_url_prefix.setObjectName(_fromUtf8("opt_url_prefix"))
        self.gridLayout_5.addWidget(self.opt_url_prefix, 8, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.start_button = QtGui.QPushButton(Form)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.horizontalLayout_2.addWidget(self.start_button)
        self.stop_button = QtGui.QPushButton(Form)
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.horizontalLayout_2.addWidget(self.stop_button)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.test_button = QtGui.QPushButton(Form)
        self.test_button.setObjectName(_fromUtf8("test_button"))
        self.horizontalLayout_2.addWidget(self.test_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.opt_autolaunch_server = QtGui.QCheckBox(Form)
        self.opt_autolaunch_server.setObjectName(_fromUtf8("opt_autolaunch_server"))
        self.verticalLayout.addWidget(self.opt_autolaunch_server)
        self.view_logs = QtGui.QPushButton(Form)
        self.view_logs.setObjectName(_fromUtf8("view_logs"))
        self.verticalLayout.addWidget(self.view_logs)
        spacerItem1 = QtGui.QSpacerItem(20, 36, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        spacerItem2 = QtGui.QSpacerItem(20, 37, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_12.setBuddy(self.opt_password)
        self.label_3.setBuddy(self.opt_max_cover)
        self.label_10.setBuddy(self.opt_port)
        self.label_11.setBuddy(self.opt_username)
        self.label_15.setBuddy(self.opt_max_opds_items)
        self.label_16.setBuddy(self.opt_max_opds_ungrouped_items)
        self.label_2.setBuddy(self.opt_url_prefix)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_("Form"))
        self.label_12.setText(_("&Password:"))
        self.opt_password.setToolTip(_("<p>If you leave the password blank, anyone will be able to\n"
" access your book collection using the web interface.\n"
"<br>\n"
"<p>Some devices have browsers that do not support authentication. If you are having trouble downloading files from the content server, try removing the password."))
        self.opt_max_cover.setToolTip(_("The maximum size (widthxheight) for displayed covers. Larger covers are resized. "))
        self.label_3.setText(_("Max. &cover size:"))
        self.label_10.setText(_("Server &port:"))
        self.label_11.setText(_("&Username:"))
        self.show_server_password.setText(_("&Show password"))
        self.label_15.setText(_("Max. &OPDS items per query:"))
        self.label_16.setText(_("Max. OPDS &ungrouped items:"))
        self.label_164.setText(_("Restriction (saved search) to apply:"))
        self.opt_cs_restriction.setToolTip(_("This restriction (based on a saved search) will restrict the books the content server makes available to those matching the search. This setting is per library (i.e. you can have a different restriction per library)."))
        self.label.setToolTip(_("<p>Some devices have browsers that do not support authentication. If you are having trouble downloading files from the content server, trying removing the password."))
        self.label.setText(_("Password incompatible with some devices"))
        self.label_2.setText(_("&URL Prefix:"))
        self.opt_url_prefix.setToolTip(_("A prefix that is applied to all URLs in the content server. Useful only if you plan to put the server behind another server like Apache, with a reverse proxy."))
        self.start_button.setText(_("&Start Server"))
        self.stop_button.setText(_("St&op Server"))
        self.test_button.setText(_("&Test Server"))
        self.label_9.setText(_("calibre contains a network server that allows you to access your book collection using a browser from anywhere in the world. Any changes to the settings will only take effect after a server restart."))
        self.opt_autolaunch_server.setText(_("Run server &automatically when calibre starts"))
        self.view_logs.setText(_("View &server logs"))
        self.label_13.setText(_("<p>Remember to leave calibre running as the server only runs as long as calibre is running.\n"
"<p>To connect to the calibre server from your device you should use a URL of the form <b>http://myhostname:8080</b> as a new catalog in the Stanza reader on your iPhone. Here myhostname should be either the fully qualified hostname or the IP address of the computer calibre is running on."))

