# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gugu/w/calibre/src/calibre/gui2/preferences/toolbar.ui'
#
# Created: Thu Jul 19 23:32:30 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(831, 553)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(Form)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.what = QtGui.QComboBox(Form)
        self.what.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.what.setMinimumContentsLength(20)
        self.what.setObjectName(_fromUtf8("what"))
        self.verticalLayout_2.addWidget(self.what)
        self.actions_widget = QtGui.QWidget(Form)
        self.actions_widget.setObjectName(_fromUtf8("actions_widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.actions_widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.actions_widget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.all_actions = QtGui.QListView(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.all_actions.sizePolicy().hasHeightForWidth())
        self.all_actions.setSizePolicy(sizePolicy)
        self.all_actions.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.all_actions.setIconSize(QtCore.QSize(32, 32))
        self.all_actions.setSpacing(10)
        self.all_actions.setWordWrap(True)
        self.all_actions.setObjectName(_fromUtf8("all_actions"))
        self.verticalLayout.addWidget(self.all_actions)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.add_action_button = QtGui.QToolButton(self.actions_widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(I("forward.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_action_button.setIcon(icon)
        self.add_action_button.setIconSize(QtCore.QSize(24, 24))
        self.add_action_button.setObjectName(_fromUtf8("add_action_button"))
        self.verticalLayout_3.addWidget(self.add_action_button)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.remove_action_button = QtGui.QToolButton(self.actions_widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(I("back.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_action_button.setIcon(icon1)
        self.remove_action_button.setIconSize(QtCore.QSize(24, 24))
        self.remove_action_button.setObjectName(_fromUtf8("remove_action_button"))
        self.verticalLayout_3.addWidget(self.remove_action_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtGui.QGroupBox(self.actions_widget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.current_actions = QtGui.QListView(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.current_actions.sizePolicy().hasHeightForWidth())
        self.current_actions.setSizePolicy(sizePolicy)
        self.current_actions.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.current_actions.setIconSize(QtCore.QSize(32, 32))
        self.current_actions.setSpacing(10)
        self.current_actions.setWordWrap(True)
        self.current_actions.setObjectName(_fromUtf8("current_actions"))
        self.horizontalLayout.addWidget(self.current_actions)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.action_up_button = QtGui.QToolButton(self.groupBox_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(I("arrow-up.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_up_button.setIcon(icon2)
        self.action_up_button.setIconSize(QtCore.QSize(24, 24))
        self.action_up_button.setObjectName(_fromUtf8("action_up_button"))
        self.verticalLayout_4.addWidget(self.action_up_button)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.action_down_button = QtGui.QToolButton(self.groupBox_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(I("arrow-down.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_down_button.setIcon(icon3)
        self.action_down_button.setIconSize(QtCore.QSize(24, 24))
        self.action_down_button.setObjectName(_fromUtf8("action_down_button"))
        self.verticalLayout_4.addWidget(self.action_down_button)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.actions_widget)
        self.spacer_widget = QtGui.QWidget(Form)
        self.spacer_widget.setObjectName(_fromUtf8("spacer_widget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.spacer_widget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(20, 224, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.spacer_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_("Form"))
        self.label.setText(_("<p>The toolbar in calibre is different depending on whether a device is connected or not. Choose <b>which toolbar</b> you would like to customize:"))
        self.what.setToolTip(_("Choose the toolbar to customize"))
        self.groupBox.setTitle(_("A&vailable actions"))
        self.add_action_button.setToolTip(_("Add selected actions to toolbar"))
        self.add_action_button.setText(_("..."))
        self.remove_action_button.setToolTip(_("Remove selected actions from toolbar"))
        self.remove_action_button.setText(_("..."))
        self.groupBox_2.setTitle(_("&Current actions"))
        self.action_up_button.setToolTip(_("Move selected action up"))
        self.action_up_button.setText(_("..."))
        self.action_down_button.setToolTip(_("Move selected action down"))
        self.action_down_button.setText(_("..."))
        self.action_down_button.setShortcut(_("Ctrl+S"))


